---

# Variables for role keepalived

keepalived_auth_pass: "1111"
keepalived_role: "MASTER"
keepalived_priority: "100"
keepalived_router_id: "52"
keepalived_shared_iface: "enp0s3"
keepalived_check_service: "haproxy"
